---
_extends: .github:common-settings.yaml

repository:
  name: agent
  description: '@fro-bot Agent'
  topics:
    - fro-bot
    - agent
    - automation
    - actions
    - github-actions
    - github-app
    - bot

branches:
  - name: main
    protection:
      enforce_admins: true
      required_linear_history: true
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts:
          - Analyze
          - Build
          - CodeQL
          - Dependency Review
          - Lint
          - Release
          - Test
          - Test GitHub Action
          - Setup
          - Renovate / Renovate

      restrictions: null

  - name: v?
    protection:
      enforce_admins: true
      required_linear_history: false
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
